### ISSUE TITLE
Threading Error Tested With and Without Mods

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TehNut/LaunchGui#5]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 4/22/15 7:34 AM
Description: Initializing game

java.lang.RuntimeException: java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-7,5,] already has the context current
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:380)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:344)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-7,5,] already has the context current
    at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
    at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:189)
    at org.lwjgl.opengl.DrawableGL.makeCurrent(DrawableGL.java:110)
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:372)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:380)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:344)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 457544272 bytes (436 MB) / 1180897280 bytes (1126 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.118.1389 Minecraft Forge 10.13.3.1389 Optifine OptiFine_1.7.10_HD_U_B6 116 mods loaded, 116 mods active

**Comment by TehNut** [comment]
I develop for the recommended version of Forge. Use that.

**Comment by P3rf3ctXZer0** [comment]
I never do because there are always bug fixes. Also they fixed a tremendous memory leak. Anyways I don't believe your mod was an issue. I think it goes deeper than that. Yeah the latest got a bonus 60 fps. Bringing frames per second with Optifine - Fastcraft and Latest version of forge to a total of 330 fps. Meaning my weaker pc players should get about 120fps

**Comment by TehNut** [comment]
I never do, either. But the majority of users are on the recommended version, so I dev for it to make sure it is compatible.

**Comment by TehNut** [comment]
I am unable to reproduce on Forge 1389 in my dev environment.

![Latest Forge](http://tehnut.info/share/Vw2VO3DC3.png)

**Comment by P3rf3ctXZer0** [comment]
Its optifine. I just contacted the owner.
